[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

# Solidity compiler
solc_version = "0.8.24"

# Optimizer
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
0g-testnet = "https://evmrpc-testnet.0g.ai"
0g-mainnet = "https://evmrpc.0g.ai"

[etherscan]
0g-testnet = { key = "", url = "https://chainscan-galileo.0g.ai/api" }
